### PR TITLE
Created a presentation on black holes

### PR DESCRIPTION
**Pull request by VickySteeves**
Hi all!

So I made a presentation on black holes, which fixes [#9](https://github.com/openwichita/lake-afton-interactive-exhibits/issues/9). 

The images for the black hole presentation located [here](https://drive.google.com/drive/folders/0BykaIuasqCrIajMwRnFENTMybEE?usp=sharing). Let me know when you download them and add them to Dropbox so I can get rid of them on mine :smile: 

This was really fun. Thanks for tagging for hacktoberfest! I used to work in a natural history museum, so this was totally up my alley!

### CODE REVIEW

**Comment by infernocloud** [comment]
Awesome, thank you for contributing! We should review and merge in your changes this week and when we do that we will move the images over.

**Comment by DJSethDuncan** [comment]
Would you mind adding a link in index.html to this presentation? There's already a few links there for reference. Thanks!

**Comment by VickySteeves** [comment]
Hi all! So I thought I did this, working from your README? 

```The files in this repo will be hosted on a server on-site using a static IP of 192.168.1.200 - make sure "home" links point there.```

What I have is this:

```
<div class="nav">
      <ul>
	  <li><a href="http://192.168.1.200">Home</a></li>
      </ul>
</div>
```

Which is what the rest of the presentations. Should I add a link -- is that what you mean?

**Comment by DJSethDuncan** [comment]
Sorry, I mean in the root folder, there's an index.html file that has this code in it: 

`<ul>
				<li><a href="/presentations/planets/mercury.html">Mercury</a></li>
        <li><a href="/presentations/planets/mars.html">Mars</a></li>
        <li><a href="/presentations/planets/saturn.html">Saturn</a></li>
        <li><a href="/presentations/keplerslaws/keplerslaws.html">Kepler's Laws</a></li>
      </ul>`


Just need to add your black hole presentation to that list.

**Comment by VickySteeves** [comment]
Oh ok! Doi. Thanks for clarifying! I'll add that now.

**Comment by VickySteeves** [comment]
Fixed! Thanks!

**Pull request merged**
